### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by evelyn-santiago** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-e-n-a#1]
[Reporte de la Entrevista.pdf](https://github.com/user-attachments/files/17564279/Reporte.de.la.Entrevista.pdf)

**Comment by Ariadnamonserrat10** [comment]
22 de 30 ya que segun la rubrica no cumple con una buena descripcion del proceso , tiene texto redundante y no cumple con el limite de la conclusion

**Comment by josealfredo79** [comment]
Revisado..
